- hosts: all
  sudo: yes
  tasks:
    - name: Configure hosts file
      lineinfile:
        regexp: "{{item}}"
        line: "{{ hostvars[item].ansible_eth1.ipv4.address }}"
        dest: /etc/hosts
      with_items: "{{ groups.all }}"
    - name: Configure resolv.conf
      template:
        src: templates/resolv.conf.j2
        dest: /etc/resolv.conf
- hosts: master
  sudo: yes
  roles:
    - zookeeper
    - mesos-master
    - chronos
    - marathon
    - geerlingguy.java
    - geerlingguy.jenkins

- hosts: slave
  sudo: yes
  roles:
    - mesos-slave
    - spark-worker
